version: '3.8'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data:/data # Persistent storage for models
    command: >
      sh -c "ollama list || true && ollama pull llama2"
    restart: unless-stopped